<section class="contmention">
    <div class="mention">
        <h1>Conditions générales d'utilisation</h1>

        <p>Les présentes conditions générales d'utilisation régissent l'utilisation du site internet Doctowebline édité par la société Doctowebline SAS , dont le siège social est situé a 13000 Marseille, France.</p>

        <h2>Objet du site</h2>
        <p>Le site Doctowebline a pour objet de proposer des services de prise de rendez-vous en ligne pour des professionnels de santé. Les utilisateurs peuvent rechercher des professionnels de santé, prendre rendez-vous en ligne et gérer leurs rendez-vous via le site.</p>

        <h2>Acceptation des conditions générales d'utilisation</h2>
        <p>Toute utilisation du site implique l'acceptation sans réserve des présentes conditions générales d'utilisation. L'utilisateur reconnaît avoir pris connaissance des présentes conditions générales d'utilisation et s'engage à les respecter.</p>

        <h2>Responsabilité de l'utilisateur</h2>
        <p>L'utilisateur est responsable de l'utilisation qu'il fait du site. L'éditeur ne saurait être tenu responsable de toute utilisation illicite ou contraire aux présentes conditions générales d'utilisation. L'utilisateur s'engage à ne pas utiliser le site à des fins illicites ou nuisibles.</p>

        <h2>Responsabilité de l'éditeur</h2>
        <p>L'éditeur ne saurait être tenu responsable de tout dommage direct ou indirect, quelles qu'en soient les causes, origines, natures ou conséquences, résultant de l'accès au site ou de son utilisation, y compris l'inaccessibilité, les pertes de données, détériorations, destructions ou virus qui pourraient affecter votre équipement informatique, et/ou de la présence de virus sur son site.</p>

        <h2>Propriété intellectuelle</h2>
        <p>Tous les éléments du site Doctowebline, qu'ils soient visuels ou sonores, y compris la technologie sous-jacente, sont protégés par le droit d'auteur, des marques ou des brevets. Ils sont la propriété exclusive de la société Doctowebline ou de ses partenaires. Toute reproduction, représentation, diffusion ou exploitation de ces éléments est interdite sans l'autorisation expresse de la société Doctowebline.</p>

        <h2>Modification des conditions générales d'utilisation</h2>
        <p>L'éditeur se réserve le droit de modifier les présentes conditions générales d'utilisation à tout moment. Les modifications entrent en vigueur dès leur publication sur le site.</p>

        <h2>Droit applicable et juridiction compétente</h2>
        <p>Les présentes conditions générales d'utilisation sont soumises au droit français. Tout litige relatif à l'interprétation ou à lexécution des présentes conditions générales d'utilisation sera de la compétence exclusive des tribunaux de Paris, France.</p>

        <h2>Contact</h2>
        <p>Pour toute question ou réclamation concernant le site, l'utilisateur peut contacter l'éditeur par email à l'adresse contact@doctowebline.com ou par courrier postal à l'adresse suivante : Doctowebline SAS, 13000 Marseille, France.</p>
    </div>
</section>