<section class="main-section">
  <div class="main-section-left">
    <img src="public/img/pexels-karolina-grabowska-5207102.jpg" alt="Docteur" class="circular-image">
  </div>
  <div class="main-section-right">
    <h2>Votre santé <br> <span>Notre priorité </span></h2>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis dolorum magni ullam, nesciunt suscipit labore, amet optio vero quo eius enim quod sapiente consequuntur est ratione repellat autem unde adipisci?</p>
    <div class="buttons-container">
      <button class="premier"><a href="#LocaliserDesDocteurs">Localiser Des Docteurs <i class="fa-sharp fa-solid fa-location-dot fa-shake"></i></a></button>
      <button class="deux"><a href="#AboutUs">About Us <i class="fa-solid fa-users"></i></a></button>
    </div>
  </div>
</section>

</header>
<section>
  <div class="second">
    <div class="box1">
      <div class="box1-ctn">
        <i class="fa-solid fa-clock"></i>
        <h3 class="titre-box1">N'importe Quand</h3>
        <p class="sous-titre-box1">Lorem ipsum dolor sit amet, consectetur</br> adipisicing elit, sed do eiusm od tempor</br> incididunt ut labore et dolore magna aliqua</br> ut enim adminim.</p>
      </div>
    </div>

    <div class="box2">
      <div class="box2-ctn">
        <i class="fa-solid fa-map-location-dot"></i>
        <h3 class="titre-box2">N'importe Où</h3>
        <p class="sous-titre-box2">Lorem ipsum dolor sit amet, consectetur</br> adipisicing elit, sed do eiusm od tempor</br> incididunt ut labore et dolore magna aliqua</br> ut enim adminim.</p>
      </div>
    </div>
    <div class="box3">
      <div class="box3-ctn">
        <i class="fa-solid fa-stethoscope"></i>
        <h3 class="titre-box3">Toutes spécialités</h3>
        <p class="sous-titre-box3">Lorem ipsum dolor sit amet, consectetur</br> adipisicing elit, sed do eiusm od tempor</br> incididunt ut labore et dolore magna aliqua</br> ut enim adminim.</p>
      </div>
    </div>
  </div>
</section>

<section class="Aboutus" id="AboutUs">

  <div class="icon">
    <i class="fa-solid fa-heart fa-beat"></i>
  </div>

  <h2 class="title">À propos de nous</h2>

  <p class="description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse quis sapien sit amet elit cursus bibendum. In a quam quis magna maximus dictum. Fusce at velit vel mauris rutrum consectetur. Sed varius, velit vitae pharetra vestibulum, nisl enim blandit felis, a ultrices justo mi quis risus.</p>

</section>

<section class="choose-us-section">
  <div class="image-container">
    <img src="public/img/pexels-karolina-grabowska-4021769.jpg" alt="Docteur">
  </div>
  <div class="text-container">
    <h2>Pourquoi choisir <span> Doctowebline </span><i class="fa-solid fa-question fa-bounce"></i></h2>
    <div class="points-container">
      <div class="point">
        <i class="fa-solid fa-circle-check"></i>
        <h3 class="title">Expertise</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis dolorum <br> magni ullam,nesciunt suscipit labore.</p>
      </div>
      <div class="point">
        <i class="fa-solid fa-circle-check"></i>
        <h3 class="title">Efficacité</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis dolorum <br> magni ullam,nesciunt suscipit labore.</p>
      </div>
      <div class="point">
        <i class="fa-solid fa-circle-check"></i>
        <h3 class="title">Rapidité</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis dolorum <br> magni ullam,nesciunt suscipit labore.</p>
      </div>
    </div>
  </div>
</section>

<section class="find" id="LocaliserDesDocteurs">

  <div class="map-container">

    <h1>Trouvez des docteurs près de chez vous ! <br> <i class="fa-sharp fa-solid fa-location-dot fa-flip"></i> </h1>

    <button id="find-me">Localiser des docteurs</button><br />
    <iframe id="map-iframe" style="border:0" loading="lazy" allowfullscreen></iframe>
    <p id="status"></p>

  </div>

</section>