<section class="mention">

    <h1>Mentions légales</h1>

    <h2>Éditeur du site</h2>
    <p>Le site Doctowebline est édité par la société Doctowebline SAS, dont le siège social est situé a 13000 Marseille, France.</p>

    <h2>Contact</h2>
    <p>Pour toute question ou demande de renseignements, vous pouvez contacter notre service client à l'adresse suivante : Doctowebline@Mail.fr.</p>

    <h2>Hébergement</h2>
    <p>Le site Doctowebline est hébergé sur les serveurs de la société Amazon Web Services, Inc., dont le siège social est situé au 410 Terry Avenue North, Seattle, WA 98109-5210, États-Unis.</p>

    <h2>Responsabilité</h2>
    <p>La société Doctowebline ne saurait être tenue responsable de tout dommage direct ou indirect, quelles qu'en soient les causes, origines, natures ou conséquences, résultant de l'accès au site ou de son utilisation, y compris l'inaccessibilité, les pertes de données, détériorations, destructions ou virus qui pourraient affecter votre équipement informatique, et/ou de la présence de virus sur son site.</p>

    <h2>Propriété intellectuelle</h2>
    <p>Tous les éléments du site Doctowebline, qu'ils soient visuels ou sonores, y compris la technologie sous-jacente, sont protégés par le droit d'auteur, des marques ou des brevets. Ils sont la propriété exclusive de la société Doctowebline ou de ses partenaires. Toute reproduction, représentation, diffusion ou exploitation de ces éléments est interdite sans l'autorisation expresse de la société Doctowebline.</p>

    <h2>Modification des mentions légales</h2>
    <p>La société Doctowebline se réserve le droit de modifier les présentes mentions légales à tout moment. Les modifications entrent en vigueur dès leur publication sur le site.</p>

    <h2>Droit applicable et juridiction compétente</h2>
    <p>Les présentes mentions légales sont soumises au droit français. Tout litige relatif à l'interprétation ou à l'exécution des présentes sera soumis à la compétence exclusive des tribunaux français.</p>

</section>