<section class="Gereruser">

    <h1>Liste des utilisateurs</h1>


    <div class="Docteurs">
        <?php if (empty($users)) : ?>
            <p>Aucun utilisateurs n'a été trouvé.</p>
        <?php else : ?>
            <table>
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nom</th>
                        <th>Prénom</th>
                        <th>Email</th>
                        <th>Date de naissance</th>
                        <th>Rôle</th>
                        <th>Modifier</th>
                        <th>Supprimer</th>

                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($users as $user) : ?>
                        <tr>
                            <td><?= $user['id'] ?></td>
                            <td><?= $user['nom'] ?></td>
                            <td><?= $user['prenom'] ?></td>
                            <td><?= $user['email'] ?></td>
                            <td><?= date_format(date_create($user['date_naissance']), 'd/m/Y') ?></td>
                            <td><?= $user['isAdmin'] ?></td>
                            <td>

                                <?php if ($_SESSION['isAdmin'] == 2) : ?>

                                    <form method="post" action="updateUser">
                                        <input type="hidden" name="user_id" value="<?= $user['id'] ?>">

                                        <select name="role" id="role">
                                            <option value="0" <?= ($user['isAdmin'] == 0) ? 'selected' : '' ?>>Utilisateur normal</option>
                                            <option value="1" <?= ($user['isAdmin'] == 1) ? 'selected' : '' ?>>Admin</option>
                                            <option value="2" <?= ($user['isAdmin'] == 2) ? 'selected' : '' ?>>Super admin</option>
                                        </select>
                                        <input type="submit" name="submit" value="Enregistrer">
                                    </form>
                                <?php endif; ?>

                            </td>
                            <td><a href="deleteUser?user_id=<?= $user['id'] ?>"><i class="fas fa-trash-alt"></i></a></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        <?php endif; ?>


    </div>

</section>