<section class="Gereruser">

    <h1>Liste des utilisateurs</h1>


    <div class="Docteurs">
        <?php if (empty($users)) : ?>
            <p>Aucun utilisateurs n'a été trouvé.</p>
        <?php else : ?>
            <table>
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nom</th>
                        <th>Prénom</th>
                        <th>Email</th>
                        <th>Âge</th>
                        <th>Rôle</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($users as $user) : ?>
                        <tr>
                            <td><?= $user['id'] ?></td>
                            <td><?= $user['nom'] ?></td>
                            <td><?= $user['prenom'] ?></td>
                            <td><?= $user['email'] ?></td>
                            <td><?= getUserAge($pdo, $user['id']) ?></td>
                            <td><?= $user['role'] ?></td>
                            <td><a href="deleteUser?user_id=<?= $user['id'] ?>">Supprimer</a></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        <?php endif; ?>


    </div>

</section>